from ArvoreBinariaBusca import ArvoreBinaria, No


arv = ArvoreBinaria('A')
arv.add('D')
arv.add('F')
arv.add('G')
arv.add('H')
arv.add('K')
arv.add('M')
arv.add('F')
print('Len: ', len(arv))
print('Imprimindo em preordem() a arvore completa')
arv.preordem()
print('\nRemove "G"')
arv.removeNo('G')
arv.preordem()
print('\nRemove "F"')
arv.removeNo('F')
arv.preordem()
print('\nRemove "H"')
arv.removeNo('H')
arv.preordem()
print('\nRemove "A"')
arv.removeNo('A')
arv.preordem()
print('\nRemove "D"')
arv.removeNo('D')
arv.preordem()
print('\nRemove "F"')
arv.removeNo('F')
arv.preordem()
print('\nRemove "M"')
arv.removeNo('M')
arv.preordem()
print('\nRemove "K"')
arv.removeNo('K')
arv.preordem()
print('\nLen: ', len(arv))

print('Remove "A"')
arv.removeNo('A')
arv.preordem()

print('\nBusca "H":', arv.busca('H'))

