from ArvoreBinariaBusca import ArvoreBinaria,Origem, No

arv2  = ArvoreBinaria()
arv = ArvoreBinaria('A')

#arv.preordem(Origem.RAIZ)
arv.addFilhoEsquerdo('D')
arv.addFilhoDireito('F')
arv.descerEsquerda()
print('Cursor: ', arv.getCursor())
arv.addFilhoEsquerdo('G')
arv.descerEsquerda()
print('Cursor: ', arv.getCursor())
arv.addFilhoDireito('H')
arv.resetCursor()
arv.descerDireita()
print('Cursor: ', arv.getCursor())
arv.addFilhoEsquerdo('K')
arv.addFilhoDireito('M')
arv.descerEsquerda()
print('Cursor: ', arv.getCursor())
arv.addFilhoEsquerdo('F')
print('Len: ', len(arv))
arv.preordem()
arv.addFilhoEsquerdo('Z')
print()
arv.preordem()
print('\nBusca "K":', arv.busca('K'))
print('Cursor: ', arv.getCursor())
arv.removeNo('F')
arv.preordem()
print('\nCursor: ', arv.getCursor())
arv.removeNo('K')
arv.preordem()
print('Len: ', len(arv))
print('RemoveRaiz():', arv.removeRaiz())

no = arv.go('K')
print(no)

